#!/usr/bin/env python3
"""Rohi — the resident profile monkey, living his life in real time.

Renders dist/monkey-life.svg: a hand-drawn vector monkey (no emoji) in a
layered jungle scene, doing whatever a monkey does at this hour in
Charlotte, NC — asleep at night, breakfast at dawn, canopy-swinging,
zoomies, juggling, tree-hopping. Sky matches the real hour; today's
contribution count is his banana feed.

Animated SVG (SMIL). Stdlib only. Regenerated by Actions every 2h.
Set ROHI_ACT=<activity> to force a pose when testing locally.
"""
import datetime
import json
import os
import urllib.request
import zoneinfo

USER = "rohithkandula19"
OUT = os.path.join(os.path.dirname(__file__), "..", "dist", "monkey-life.svg")
W, H = 900, 300
GROUND_Y = 240

FUR = "#8a5a32"
FUR_D = "#6d4423"
SKIN = "#d9b48a"
SKIN_D = "#c9a273"
DARK = "#2b1b10"


# ---------------------------------------------------------------- character
def head(eyes="open", tilt=0, bob=False):
    """Head at local origin = head centre, facing right."""
    if eyes == "open":
        eye_parts = ""
        for ex in (-1, 7):
            eye_parts += (
                f'<ellipse cx="{ex}" cy="-1" rx="2.6" ry="3.2" fill="#fff"/>'
                f'<circle cx="{ex + 0.8}" cy="-0.6" r="1.5" fill="{DARK}"/>'
                f'<circle cx="{ex + 1.4}" cy="-1.4" r="0.55" fill="#fff"/>'
            )
        # slow blink
        eye_parts += (
            f'<g fill="{SKIN}"><rect x="-5" y="-5" width="16" height="0" rx="2">'
            f'<animate attributeName="height" values="0;0;8;0;0" keyTimes="0;0.9;0.94;0.98;1" '
            f'dur="6s" repeatCount="indefinite"/></rect></g>'
        )
    else:
        eye_parts = (
            f'<path d="M -3.4,-1 q 2.4,2.2 4.8,0" fill="none" stroke="{DARK}" stroke-width="1.1" stroke-linecap="round"/>'
            f'<path d="M 4.6,-1 q 2.4,2.2 4.8,0" fill="none" stroke="{DARK}" stroke-width="1.1" stroke-linecap="round"/>'
        )
    bob_anim = (
        '<animateTransform attributeName="transform" type="translate" '
        'values="0,0;0,1.6;0,0" dur="1.1s" repeatCount="indefinite" additive="sum"/>'
        if bob else ""
    )
    return (
        f'<g transform="rotate({tilt})">{bob_anim}'
        f'<circle cx="-12" cy="-3" r="6" fill="{FUR}"/><circle cx="-12" cy="-3" r="3" fill="{SKIN_D}"/>'
        f'<circle cx="12" cy="-3" r="6" fill="{FUR}"/><circle cx="12" cy="-3" r="3" fill="{SKIN_D}"/>'
        f'<circle cx="0" cy="0" r="13" fill="{FUR}"/>'
        f'<path d="M -10,-8 q 10,-7 20,0 q -4,-3 -10,-3 q -6,0 -10,3 z" fill="{FUR_D}" opacity="0.6"/>'
        f'<ellipse cx="3" cy="3.5" rx="9.5" ry="8" fill="{SKIN}"/>'
        + eye_parts +
        f'<circle cx="5" cy="4.6" r="0.8" fill="{FUR_D}"/><circle cx="7.4" cy="4.6" r="0.8" fill="{FUR_D}"/>'
        f'<path d="M 2,8 q 4.5,3.4 9,0" fill="none" stroke="{FUR_D}" stroke-width="1.2" stroke-linecap="round"/>'
        f"</g>"
    )


def tail(base=(-13, -26), sway=10, dur=3.2):
    bx, by = base
    return (
        f'<g transform="translate({bx},{by})">'
        f'<animateTransform attributeName="transform" type="rotate" '
        f'values="-{sway} 0 0;{sway} 0 0;-{sway} 0 0" dur="{dur}s" repeatCount="indefinite" additive="sum"/>'
        f'<path d="M 0,0 C -16,-2 -26,-18 -18,-30 C -14,-36 -6,-36 -6,-30" '
        f'fill="none" stroke="{FUR}" stroke-width="6.5" stroke-linecap="round"/></g>'
    )


def limb(x, y, angle, length=20, width=7, color=FUR, swing=None):
    """Capsule limb hung from (x, y), rotated `angle`° from straight down."""
    anim = (
        f'<animateTransform attributeName="transform" type="rotate" '
        f'values="{swing[0]} 0 0;{swing[1]} 0 0;{swing[0]} 0 0" dur="{swing[2]}s" '
        f'repeatCount="indefinite" additive="sum"/>'
        if swing else ""
    )
    return (
        f'<g transform="translate({x},{y}) rotate({angle})">{anim}'
        f'<path d="M 0,0 Q 1.5,{length * 0.55} 0,{length}" fill="none" '
        f'stroke="{color}" stroke-width="{width}" stroke-linecap="round"/>'
        f'<circle cx="0" cy="{length}" r="{width * 0.52}" fill="{SKIN_D}"/></g>'
    )


def body():
    return (
        f'<ellipse cx="0" cy="-26" rx="15" ry="19" fill="{FUR}"/>'
        f'<ellipse cx="3" cy="-22" rx="9.5" ry="12.5" fill="{SKIN_D}"/>'
    )


def monkey_sit(eat=False, arms_up=False, eyes="open"):
    """Sitting monkey, origin at seat/ground."""
    arm_back = limb(-6, -38, 18, 19)
    if eat:
        # right arm pumps banana to mouth
        arm_front = (
            f'<g transform="translate(7,-38)">'
            f'<animateTransform attributeName="transform" type="rotate" '
            f'values="-118 0 0;-150 0 0;-118 0 0" dur="1.1s" repeatCount="indefinite" additive="sum"/>'
            f'<path d="M 0,0 Q 1.5,10 0,19" fill="none" stroke="{FUR}" stroke-width="7" stroke-linecap="round"/>'
            f'<g transform="translate(0,21) rotate(40)">'
            f'<path d="M -5,0 Q 0,-5 5,0 Q 0,2.5 -5,0 z" fill="#f5d547" stroke="#caa92f" stroke-width="0.7"/></g></g>'
        )
        head_g = f'<g transform="translate(5,-54)">{head(eyes=eyes, bob=True)}</g>'
    elif arms_up:
        arm_front = limb(7, -38, -150, 19, swing=(-8, 8, 0.9))
        arm_back = limb(-6, -38, 150, 19, swing=(8, -8, 0.9))
        head_g = f'<g transform="translate(5,-54)">{head(eyes=eyes)}</g>'
    else:
        arm_front = limb(7, -38, 8, 19)
        head_g = f'<g transform="translate(5,-54)">{head(eyes=eyes)}</g>'
    legs = (
        f'<path d="M -4,-12 Q 8,-14 14,-6 Q 16,-2 12,-1 Q 2,-4 -4,-6 z" fill="{FUR_D}"/>'
        f'<circle cx="13" cy="-3" r="3.6" fill="{SKIN_D}"/>'
    )
    return tail() + arm_back + body() + legs + arm_front + head_g


def monkey_lie():
    """Asleep on his side — whole sitting pose laid down, chest rising."""
    return (
        f'<g transform="rotate(-84) translate(6,2)">'
        f'<animateTransform attributeName="transform" type="scale" values="1;1.025;1" '
        f'dur="4s" repeatCount="indefinite" additive="sum"/>'
        + monkey_sit(eyes="closed") +
        f"</g>"
    )


def monkey_hang():
    """Hanging by both arms (for the vine), origin at the grip point."""
    return (
        f'<g>'
        f'{limb(-5, 2, 168, 20)}{limb(5, 2, 192, 20)}'
        f'<g transform="translate(0,38)">'
        f'<ellipse cx="0" cy="-14" rx="13" ry="17" fill="{FUR}"/>'
        f'<ellipse cx="2" cy="-11" rx="8" ry="11" fill="{SKIN_D}"/>'
        f'{limb(-5, -2, 28, 16)}{limb(6, -2, -20, 16)}'
        f'<g transform="translate(-11,-6)"><path d="M 0,0 C -12,4 -20,-6 -14,-16" fill="none" stroke="{FUR}" stroke-width="6" stroke-linecap="round">'
        f'</path></g>'
        f'<g transform="translate(2,-36)">{head()}</g>'
        f"</g></g>"
    )


def monkey_run():
    """Galloping profile, origin at ground under the chest."""
    return (
        f'<g transform="rotate(14)">'
        + tail(base=(-16, -30), sway=6, dur=0.8)
        + limb(-8, -34, 40, 20, swing=(28, -34, 0.42))
        + f'<ellipse cx="0" cy="-30" rx="17" ry="14" fill="{FUR}"/>'
        f'<ellipse cx="3" cy="-27" rx="10" ry="8.5" fill="{SKIN_D}"/>'
        + limb(-10, -22, -30, 18, swing=(-26, 30, 0.42))
        + limb(9, -22, 24, 18, swing=(30, -26, 0.42))
        + limb(10, -34, -36, 20, swing=(-30, 28, 0.42))
        + f'<g transform="translate(17,-44) rotate(-14)">{head(bob=True)}</g>'
        f"</g>"
    )


def monkey_jump():
    """Stretched mid-leap, origin at chest."""
    return (
        f'<g transform="rotate(-18)">'
        + tail(base=(-15, 2), sway=14, dur=1.4)
        + limb(-12, -4, 130, 20)
        + limb(-8, -8, 118, 20)
        + f'<ellipse cx="0" cy="-8" rx="17" ry="13" fill="{FUR}"/>'
        f'<ellipse cx="3" cy="-6" rx="10" ry="8" fill="{SKIN_D}"/>'
        + limb(10, -14, -118, 20)
        + limb(13, -10, -132, 20)
        + f'<g transform="translate(19,-22) rotate(10)">{head()}</g>'
        f"</g>"
    )


# ------------------------------------------------------------------- scene
def sky(hour):
    night = hour >= 21 or hour < 6
    twilight = hour in (6, 7, 19, 20)
    if night:
        top, bottom = "#0b1d3a", "#1b2f55"
    elif twilight:
        top, bottom = "#3a2b63", "#ff9e64"
    else:
        top, bottom = "#7ec8f0", "#dff3ff"
    parts = [
        f'<defs>'
        f'<linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">'
        f'<stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/></linearGradient>'
        f'<radialGradient id="glow"><stop offset="0" stop-color="#fff7c9" stop-opacity="0.9"/>'
        f'<stop offset="1" stop-color="#fff7c9" stop-opacity="0"/></radialGradient>'
        f'<radialGradient id="moonglow"><stop offset="0" stop-color="#cdd9f0" stop-opacity="0.55"/>'
        f'<stop offset="1" stop-color="#cdd9f0" stop-opacity="0"/></radialGradient>'
        f'</defs>'
        f'<rect width="{W}" height="{H}" rx="16" fill="url(#sky)"/>'
    ]
    if night:
        parts.append(
            '<circle cx="600" cy="62" r="46" fill="url(#moonglow)"/>'
            '<circle cx="600" cy="62" r="20" fill="#e8eefb"/>'
            '<circle cx="593" cy="56" r="4.5" fill="#cfd9ee"/>'
            '<circle cx="606" cy="66" r="3" fill="#cfd9ee"/>'
            '<circle cx="600" cy="48" r="2.2" fill="#cfd9ee"/>'
        )
        for i, (sx, sy) in enumerate(
            [(70, 40), (160, 72), (260, 34), (370, 58), (470, 38), (700, 50), (780, 28), (850, 80), (520, 90)]
        ):
            parts.append(
                f'<circle cx="{sx}" cy="{sy}" r="1.7" fill="#fff">'
                f'<animate attributeName="opacity" values="0.2;1;0.2" dur="{2.4 + i * 0.4:.1f}s" '
                f'repeatCount="indefinite" begin="{i * 0.3:.1f}s"/></circle>'
            )
        for i, fx in enumerate((230, 470, 690)):
            parts.append(
                f'<circle cx="{fx}" cy="{GROUND_Y - 34}" r="2.2" fill="#d9f99d">'
                f'<animate attributeName="opacity" values="0;1;0" dur="{3 + i}s" repeatCount="indefinite" begin="{i * 1.2:.1f}s"/>'
                f'<animate attributeName="cy" values="{GROUND_Y - 28};{GROUND_Y - 62};{GROUND_Y - 28}" dur="{7 + i}s" repeatCount="indefinite"/></circle>'
            )
    elif twilight:
        parts.append(
            '<circle cx="600" cy="80" r="52" fill="url(#glow)"/>'
            '<circle cx="600" cy="80" r="19" fill="#ffd56b"/>'
        )
    else:
        parts.append(
            '<circle cx="600" cy="64" r="58" fill="url(#glow)"/>'
            '<circle cx="600" cy="64" r="21" fill="#ffd94d"/>'
            '<g opacity="0.95" fill="#ffffff">'
            '<g><ellipse cx="0" cy="0" rx="26" ry="9"/><ellipse cx="18" cy="-6" rx="18" ry="8"/>'
            f'<animateMotion dur="70s" repeatCount="indefinite" path="M 120,52 H {W - 80} H 120"/></g></g>'
        )
        # distant birds
        parts.append(
            '<g stroke="#46606e" stroke-width="1.6" fill="none" stroke-linecap="round">'
            '<g><path d="M -6,0 Q -2,-4 0,0 Q 2,-4 6,0"/>'
            f'<animateMotion dur="34s" repeatCount="indefinite" path="M -20,84 q {W / 2},-26 {W + 40},10"/></g>'
            '<g><path d="M -5,0 Q -1.5,-3.4 0,0 Q 1.5,-3.4 5,0"/>'
            f'<animateMotion dur="34s" begin="1.6s" repeatCount="indefinite" path="M -20,98 q {W / 2},-22 {W + 40},14"/></g></g>'
        )
    return "".join(parts), night


def backdrop(night):
    """Distant jungle canopy band for depth."""
    fill = "#11301a" if night else "#1f7032"
    blobs = "".join(
        f'<circle cx="{x}" cy="{GROUND_Y - 18}" r="{r}" fill="{fill}" opacity="0.45"/>'
        for x, r in [(40, 34), (120, 46), (220, 38), (330, 50), (445, 40), (560, 48), (680, 38), (790, 50), (870, 36)]
    )
    return blobs


def ground(night):
    g1 = "#1c4023" if night else "#2e8b3d"
    g2 = "#163319" if night else "#247232"
    blades = "".join(
        f'<path d="M {x},{GROUND_Y + 6} q 2,-12 {dx},-16" fill="none" stroke="{g2}" stroke-width="2" stroke-linecap="round"/>'
        for x, dx in [(70, 3), (75, -2), (250, 2), (256, -3), (420, 3), (610, -2), (616, 3), (840, 2), (846, -2)]
    )
    rocks = (
        f'<ellipse cx="520" cy="{GROUND_Y + 10}" rx="14" ry="6" fill="{"#3a4750" if night else "#8d99a6"}"/>'
        f'<ellipse cx="540" cy="{GROUND_Y + 13}" rx="8" ry="4" fill="{"#2f3a42" if night else "#7c8894"}"/>'
    )
    flowers = "" if night else (
        f'<circle cx="150" cy="{GROUND_Y + 14}" r="3" fill="#ffd94d"/>'
        f'<circle cx="305" cy="{GROUND_Y + 18}" r="3" fill="#ff8fa3"/>'
        f'<circle cx="708" cy="{GROUND_Y + 12}" r="3" fill="#ffd94d"/>'
    )
    return (
        f'<path d="M 0,{GROUND_Y} Q {W / 2},{GROUND_Y - 12} {W},{GROUND_Y} V {H - 16} '
        f'Q {W},{H} {W - 16},{H} H 16 Q 0,{H} 0,{H - 16} z" fill="{g1}"/>'
        + blades + rocks + flowers
    )


def tree(x, night, scale=1.0):
    trunk = "#4a3420" if night else "#6b4a2b"
    trunk_hi = "#5d4329" if night else "#7d5835"
    leaf_d = "#143c1c" if night else "#23793a"
    leaf = "#1d5429" if night else "#2f9e44"
    leaf_hi = "#2a6b36" if night else "#46b85c"
    s = scale
    top = GROUND_Y - 160 * s
    return (
        f'<path d="M {x - 9 * s},{GROUND_Y + 4} C {x - 6 * s},{GROUND_Y - 70 * s} {x - 2 * s},{GROUND_Y - 100 * s} {x - 1 * s},{top + 30 * s} '
        f'L {x + 7 * s},{top + 32 * s} C {x + 7 * s},{GROUND_Y - 80 * s} {x + 9 * s},{GROUND_Y - 40 * s} {x + 11 * s},{GROUND_Y + 4} z" fill="{trunk}"/>'
        f'<path d="M {x - 2 * s},{GROUND_Y} C {x - 1 * s},{GROUND_Y - 80 * s} {x + 1 * s},{GROUND_Y - 110 * s} {x + 2 * s},{top + 34 * s}" '
        f'stroke="{trunk_hi}" stroke-width="{3 * s}" fill="none"/>'
        f'<circle cx="{x - 32 * s}" cy="{top + 22 * s}" r="{30 * s}" fill="{leaf_d}"/>'
        f'<circle cx="{x + 34 * s}" cy="{top + 24 * s}" r="{28 * s}" fill="{leaf_d}"/>'
        f'<circle cx="{x - 12 * s}" cy="{top + 2 * s}" r="{32 * s}" fill="{leaf}"/>'
        f'<circle cx="{x + 16 * s}" cy="{top + 6 * s}" r="{30 * s}" fill="{leaf}"/>'
        f'<circle cx="{x - 2 * s}" cy="{top - 6 * s}" r="{24 * s}" fill="{leaf_hi}"/>'
        f'<g transform="translate({x + 26 * s},{top + 40 * s})">'
        f'<path d="M -4,0 Q 0,-4 4,0 Q 0,2 -4,0 z" fill="#f5d547" transform="rotate(20)"/>'
        f'<path d="M -4,3 Q 0,-1 4,3 Q 0,5 -4,3 z" fill="#f0c93a"/></g>'
    ), (x, top)


def plants(night):
    leaf = "#143c1c" if night else "#23793a"
    leaf2 = "#1d5429" if night else "#2f9e44"
    out = []
    for bx, flip in ((36, 1), (864, -1)):
        fronds = "".join(
            f'<path d="M 0,0 Q {flip * dx},{-dy - 14} {flip * (dx + 16)},{-dy}" fill="none" '
            f'stroke="{leaf2 if i % 2 else leaf}" stroke-width="7" stroke-linecap="round"/>'
            for i, (dx, dy) in enumerate([(6, 38), (16, 30), (24, 18), (2, 46)])
        )
        out.append(f'<g transform="translate({bx},{GROUND_Y + 6})">{fronds}</g>')
    return "".join(out)


def butterfly():
    return (
        '<g><g>'
        '<ellipse cx="-2.6" cy="0" rx="3" ry="4" fill="#f4a8c0">'
        '<animate attributeName="rx" values="3;0.8;3" dur="0.36s" repeatCount="indefinite"/></ellipse>'
        '<ellipse cx="2.6" cy="0" rx="3" ry="4" fill="#ef8bab">'
        '<animate attributeName="rx" values="3;0.8;3" dur="0.36s" repeatCount="indefinite"/></ellipse>'
        '<rect x="-0.7" y="-3.6" width="1.4" height="7.2" rx="0.7" fill="#5a4636"/></g>'
        f'<animateMotion dur="22s" repeatCount="indefinite" '
        f'path="M 110,{GROUND_Y - 60} q 90,-40 180,-10 q 80,30 160,-16 q -120,-30 -200,6 q -80,30 -140,20 z"/></g>'
    )


# --------------------------------------------------------------- activities
def scene_for(act, t1, t2, night):
    x1, y1 = t1
    x2, y2 = t2
    mid = (x1 + x2) / 2

    if act == "sleeping":
        zs = "".join(
            f'<text x="{x1 + 64 + i * 13}" y="{GROUND_Y - 40 - i * 7}" font-size="{12 + i * 4}" '
            f'fill="#cdd9f0" font-family="ui-monospace, monospace" opacity="0">z'
            f'<animate attributeName="opacity" values="0;0.9;0" dur="3.2s" begin="{i * 1.05:.1f}s" repeatCount="indefinite"/>'
            f'<animate attributeName="y" values="{GROUND_Y - 32 - i * 7};{GROUND_Y - 64 - i * 7}" dur="3.2s" begin="{i * 1.05:.1f}s" repeatCount="indefinite"/></text>'
            for i in range(3)
        )
        return f'<g transform="translate({x1 + 46},{GROUND_Y - 2})">{monkey_lie()}</g>' + zs

    if act == "eating":
        peels = (
            f'<g transform="translate({mid - 24},{GROUND_Y - 2})">'
            f'<path d="M -6,0 Q 0,-6 6,0 Q 0,2.6 -6,0 z" fill="#f5d547" transform="rotate(-14)"/>'
            f'<path d="M 4,3 Q 10,-3 16,3 Q 10,5.4 4,3 z" fill="#f0c93a"/></g>'
        )
        return peels + f'<g transform="translate({mid + 10},{GROUND_Y - 2})">{monkey_sit(eat=True)}</g>'

    if act == "swinging":
        vine_color = "#3c5a3c" if night else "#4a7a4a"
        return (
            f'<path d="M {x1},{y1} Q {mid},{y1 + 150} {x2},{y2}" fill="none" '
            f'stroke="{vine_color}" stroke-width="3.4" stroke-linecap="round"/>'
            f'<g>{monkey_hang()}'
            f'<animateMotion dur="5.4s" repeatCount="indefinite" keyPoints="0;1;0" keyTimes="0;0.5;1" '
            f'calcMode="linear" path="M {x1},{y1 + 4} Q {mid},{y1 + 150} {x2},{y2 + 4}"/></g>'
        )

    if act == "running":
        return (
            f'<g>{monkey_run()}'
            f'<animateMotion dur="7s" repeatCount="indefinite" keyPoints="0;1;0" keyTimes="0;0.5;1" '
            f'calcMode="linear" path="M {x1 + 40},{GROUND_Y - 2} '
            f'q 45,-22 90,0 q 45,-22 90,0 q 45,-22 90,0 q 45,-22 90,0 q 45,-22 90,0 q 45,-22 90,0"/></g>'
        )

    if act == "playing":
        balls = "".join(
            f'<g><path d="M -5,0 Q 0,-5 5,0 Q 0,2.5 -5,0 z" fill="#f5d547" stroke="#caa92f" stroke-width="0.6"/>'
            f'<animateMotion dur="1.7s" begin="{i * 0.57:.2f}s" repeatCount="indefinite" '
            f'path="M {mid - 22},{GROUND_Y - 78} a 22,30 0 1 1 44,0 a 22,30 0 1 1 -44,0"/></g>'
            for i in range(3)
        )
        return f'<g transform="translate({mid},{GROUND_Y - 2})">{monkey_sit(arms_up=True)}</g>' + balls

    # jumping
    return (
        f'<g>{monkey_jump()}'
        f'<animateMotion dur="5.6s" repeatCount="indefinite" '
        f'keyPoints="0;0.45;0.5;0.95;1" keyTimes="0;0.4;0.5;0.9;1" calcMode="linear" '
        f'path="M {x1},{y1 - 20} Q {mid},{y1 - 120} {x2},{y2 - 20} Q {mid},{y2 - 120} {x1},{y1 - 20}"/></g>'
    )


ACTIVITIES = {
    "sleeping": "fast asleep",
    "eating": "having bananas",
    "swinging": "swinging through the canopy",
    "running": "doing zoomies",
    "playing": "juggling his lunch",
    "jumping": "hopping between trees",
}


def pick_activity(hour):
    if hour >= 22 or hour < 6:
        return "sleeping"
    if hour < 8:
        return "eating"
    if hour < 11:
        return "swinging"
    if hour < 13:
        return "eating"
    if hour < 16:
        return "running"
    if hour < 19:
        return "playing"
    return "jumping"


def bananas_today():
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return None
    query = """
    query($login: String!) {
      user(login: $login) {
        contributionsCollection {
          contributionCalendar { weeks { contributionDays { contributionCount date } } }
        }
      }
    }"""
    try:
        req = urllib.request.Request(
            "https://api.github.com/graphql",
            data=json.dumps({"query": query, "variables": {"login": USER}}).encode(),
            headers={"Authorization": f"Bearer {token}", "User-Agent": "rohi/2.0"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
        days = [
            d
            for w in data["data"]["user"]["contributionsCollection"]["contributionCalendar"]["weeks"]
            for d in w["contributionDays"]
        ]
        today = datetime.datetime.now(zoneinfo.ZoneInfo("America/New_York")).date().isoformat()
        return next((d["contributionCount"] for d in days if d["date"] == today), 0)
    except Exception:
        return None


def main():
    now = datetime.datetime.now(zoneinfo.ZoneInfo("America/New_York"))
    act = os.environ.get("ROHI_ACT") or pick_activity(now.hour)
    fed = bananas_today()

    sky_svg, night = sky(now.hour)
    t1_svg, t1 = tree(140, night, 1.0)
    t2_svg, t2 = tree(760, night, 0.94)

    status = f"Rohi is {ACTIVITIES[act]} · {now.strftime('%-I:%M %p')} in Charlotte"
    if fed is not None:
        status += f" · fed {fed} 🍌 today" if fed else " · hungry — a git push feeds him 🍌"

    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
        f'role="img" aria-label="Rohi the monkey, currently {ACTIVITIES[act]}">'
        + sky_svg
        + backdrop(night)
        + ground(night)
        + t1_svg
        + t2_svg
        + plants(night)
        + ("" if night else butterfly())
        + scene_for(act, t1, t2, night)
        + f'<text x="{W / 2}" y="{H - 11}" font-size="13" text-anchor="middle" '
        f'fill="{"#cdd9f0" if night else "#eaf7ec"}" font-family="ui-monospace, monospace">{status}</text>'
        + "</svg>"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"monkey-life.svg written — {act} at {now:%H:%M %Z}, fed={fed}")


if __name__ == "__main__":
    main()
