#!/usr/bin/env python3
"""Mojo — the resident profile monkey, living his life in real time.

Renders dist/monkey-life.svg: a jungle scene where Mojo does whatever a
monkey does at this hour in Charlotte, NC — sleeping at night, breakfast
at dawn, swinging, zoomies, juggling, tree-hopping. Day/night sky matches
the actual time. Commits feed him (today's contribution count = bananas).

Hand-built animated SVG (SMIL). Stdlib only. Regenerated by Actions.
"""
import datetime
import json
import os
import urllib.request
import zoneinfo

USER = "rohithkandula19"
OUT = os.path.join(os.path.dirname(__file__), "..", "dist", "monkey-life.svg")
W, H = 900, 280
GROUND_Y = 225


def bananas_today():
    """Today's contribution count — Mojo's food supply."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return None
    query = """
    query($login: String!) {
      user(login: $login) {
        contributionsCollection {
          contributionCalendar { weeks { contributionDays { contributionCount date } } }
        }
      }
    }"""
    try:
        req = urllib.request.Request(
            "https://api.github.com/graphql",
            data=json.dumps({"query": query, "variables": {"login": USER}}).encode(),
            headers={"Authorization": f"Bearer {token}", "User-Agent": "mojo/1.0"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
        days = [
            d
            for w in data["data"]["user"]["contributionsCollection"][
                "contributionCalendar"
            ]["weeks"]
            for d in w["contributionDays"]
        ]
        today = datetime.datetime.now(zoneinfo.ZoneInfo("America/New_York")).date().isoformat()
        return next((d["contributionCount"] for d in days if d["date"] == today), 0)
    except Exception:
        return None


def sky(hour):
    """Sky gradient + celestial bodies for the hour."""
    night = hour >= 21 or hour < 6
    twilight = hour in (6, 7, 19, 20)
    parts = []
    if night:
        top, bottom = "#0b1d3a", "#16294d"
    elif twilight:
        top, bottom = "#3a2b63", "#ff9e64"
    else:
        top, bottom = "#7ec8f0", "#d8f1ff"
    parts.append(
        f'<defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">'
        f'<stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/>'
        f"</linearGradient></defs>"
        f'<rect width="{W}" height="{H}" rx="16" fill="url(#sky)"/>'
    )
    if night:
        parts.append('<text x="600" y="70" font-size="40">🌙</text>')
        for i, (sx, sy) in enumerate(
            [(60, 40), (150, 70), (260, 35), (380, 60), (500, 40), (620, 75), (720, 30), (850, 95)]
        ):
            parts.append(
                f'<circle cx="{sx}" cy="{sy}" r="1.8" fill="#fff">'
                f'<animate attributeName="opacity" values="0.2;1;0.2" dur="{2.5 + i * 0.4:.1f}s" '
                f'repeatCount="indefinite" begin="{i * 0.3:.1f}s"/></circle>'
            )
        # fireflies
        for i, fx in enumerate((220, 480, 660)):
            parts.append(
                f'<circle cx="{fx}" cy="{GROUND_Y - 30}" r="2.2" fill="#d9f99d">'
                f'<animate attributeName="opacity" values="0;1;0" dur="{3 + i:.0f}s" repeatCount="indefinite" begin="{i * 1.1:.1f}s"/>'
                f'<animate attributeName="cy" values="{GROUND_Y - 25};{GROUND_Y - 55};{GROUND_Y - 25}" dur="{6 + i}s" repeatCount="indefinite"/>'
                f"</circle>"
            )
    elif twilight:
        parts.append('<text x="585" y="80" font-size="42">🌅</text>')
    else:
        parts.append(
            '<g><text x="585" y="78" font-size="44">☀️</text>'
            '<animateTransform attributeName="transform" type="rotate" '
            'values="-3 607 63;3 607 63;-3 607 63" dur="8s" repeatCount="indefinite"/></g>'
        )
        parts.append(
            '<g font-size="22" opacity="0.9"><text x="0" y="0">☁️</text>'
            f'<animateMotion dur="60s" repeatCount="indefinite" path="M 80,55 H {W - 60} H 80"/></g>'
        )
    return "".join(parts), night


def ground(night):
    fill = "#1c4023" if night else "#2e8b3d"
    deco = "" if night else (
        f'<text x="120" y="{GROUND_Y + 32}" font-size="14">🌼</text>'
        f'<text x="300" y="{GROUND_Y + 32}" font-size="14">🌱</text>'
        f'<text x="815" y="{GROUND_Y + 30}" font-size="14">🌸</text>'
    )
    return (
        f'<rect x="0" y="{GROUND_Y}" width="{W}" height="{H - GROUND_Y}" rx="16" fill="{fill}"/>'
        f'<rect x="0" y="{GROUND_Y}" width="{W}" height="12" fill="{fill}"/>' + deco
    )


def tree(x, night, scale=1.0, bananas=True):
    trunk = "#5d4023" if night else "#7a5230"
    leaf = "#1e5b2a" if night else "#2f9e44"
    leaf2 = "#174a21" if night else "#27863a"
    s = scale
    top_y = GROUND_Y - 150 * s
    parts = [
        f'<path d="M {x - 7 * s},{GROUND_Y} q {2 * s},-{90 * s} {7 * s},-{120 * s} q {5 * s},{30 * s} {7 * s},{120 * s} z" fill="{trunk}"/>',
        f'<circle cx="{x - 28 * s}" cy="{top_y + 18 * s}" r="{30 * s}" fill="{leaf2}"/>',
        f'<circle cx="{x + 28 * s}" cy="{top_y + 18 * s}" r="{30 * s}" fill="{leaf2}"/>',
        f'<circle cx="{x}" cy="{top_y}" r="{36 * s}" fill="{leaf}"/>',
    ]
    if bananas:
        parts.append(f'<text x="{x + 18 * s}" y="{top_y + 34 * s}" font-size="{14 * s:.0f}">🍌</text>')
    return "".join(parts), (x, top_y)


def monkey_scene(act, t1, t2, night):
    """Return SVG for Mojo doing `act`. t1/t2 = (x, canopy_y) of the trees."""
    x1, y1 = t1
    x2, y2 = t2
    mid = (x1 + x2) / 2

    if act == "sleeping":
        zs = "".join(
            f'<text x="{x1 + 52 + i * 12}" y="{GROUND_Y - 38 - i * 6}" font-size="{13 + i * 3}" fill="#cdd9f0" opacity="0">z'
            f'<animate attributeName="opacity" values="0;1;0" dur="3s" begin="{i}s" repeatCount="indefinite"/>'
            f'<animate attributeName="y" values="{GROUND_Y - 30 - i * 6};{GROUND_Y - 60 - i * 6}" dur="3s" begin="{i}s" repeatCount="indefinite"/>'
            f"</text>"
            for i in range(3)
        )
        return (
            f'<text x="{x1 + 30}" y="{GROUND_Y - 8}" font-size="30" transform="rotate(-90 {x1 + 38} {GROUND_Y - 16})">🐒</text>'
            f'<text x="{x1 + 14}" y="{GROUND_Y - 30}" font-size="15">💤</text>' + zs
        )

    if act == "eating":
        pile = f'<text x="{mid - 26}" y="{GROUND_Y - 4}" font-size="18">🍌🍌</text>'
        flying = (
            f'<g><text x="0" y="0" font-size="15">🍌</text>'
            f'<animateMotion dur="2.2s" repeatCount="indefinite" '
            f'path="M {mid - 14},{GROUND_Y - 10} Q {mid + 4},{GROUND_Y - 42} {mid + 20},{GROUND_Y - 26}"/>'
            f'<animate attributeName="opacity" values="1;1;0" keyTimes="0;0.8;1" dur="2.2s" repeatCount="indefinite"/></g>'
        )
        return (
            f'<text x="{mid + 12}" y="{GROUND_Y - 6}" font-size="32">🐒</text>' + pile + flying +
            f'<text x="{mid + 46}" y="{GROUND_Y - 44}" font-size="11" fill="#fff" opacity="0">nom nom'
            f'<animate attributeName="opacity" values="0;0.9;0" dur="2.2s" repeatCount="indefinite"/></text>'
        )

    if act == "swinging":
        vine = (
            f'<path d="M {x1},{y1} Q {mid},{y1 + 130} {x2},{y2}" fill="none" '
            f'stroke="{"#3c5a3c" if night else "#4a7a4a"}" stroke-width="3" stroke-linecap="round"/>'
        )
        return vine + (
            f'<g><text x="0" y="14" font-size="30" text-anchor="middle">🐒</text>'
            f'<animateMotion dur="5s" repeatCount="indefinite" keyPoints="0;1;0" keyTimes="0;0.5;1" '
            f'calcMode="linear" path="M {x1},{y1 + 6} Q {mid},{y1 + 130} {x2},{y2 + 6}"/></g>'
        )

    if act == "running":
        puffs = "".join(
            f'<text x="{px}" y="{GROUND_Y - 6}" font-size="13" opacity="0">💨'
            f'<animate attributeName="opacity" values="0;0.8;0" dur="1.6s" begin="{i * 0.8}s" repeatCount="indefinite"/></text>'
            for i, px in enumerate((mid - 120, mid + 90))
        )
        return puffs + (
            f'<g><text x="0" y="0" font-size="32" text-anchor="middle">🐒</text>'
            f'<animateMotion dur="7s" repeatCount="indefinite" keyPoints="0;1;0" keyTimes="0;0.5;1" '
            f'calcMode="linear" path="M {x1 + 20},{GROUND_Y - 10} '
            f'q 45,-26 90,0 q 45,-26 90,0 q 45,-26 90,0 q 45,-26 90,0 q 45,-26 90,0 q 45,-26 90,0"/></g>'
        )

    if act == "playing":
        balls = "".join(
            f'<g><text x="0" y="0" font-size="14">🍌</text>'
            f'<animateMotion dur="1.8s" begin="{i * 0.6}s" repeatCount="indefinite" '
            f'path="M {mid - 20},{GROUND_Y - 52} a 20,26 0 1 1 40,0 a 20,26 0 1 1 -40,0"/></g>'
            for i in range(3)
        )
        return (
            f'<text x="{mid - 16}" y="{GROUND_Y - 6}" font-size="32">🐒</text>' + balls +
            f'<g><text x="0" y="0" font-size="15">⚽</text>'
            f'<animateMotion dur="2.6s" repeatCount="indefinite" '
            f'path="M {mid + 70},{GROUND_Y - 8} q 25,-46 50,0 q -25,-22 -50,0"/></g>'
        )

    # jumping — hop from canopy to canopy with a hang-time pause
    return (
        f'<g><text x="0" y="6" font-size="30" text-anchor="middle">🐒</text>'
        f'<animateMotion dur="6s" repeatCount="indefinite" '
        f'keyPoints="0;0.45;0.5;0.95;1" keyTimes="0;0.4;0.5;0.9;1" calcMode="linear" '
        f'path="M {x1},{y1 - 14} Q {mid},{y1 - 110} {x2},{y2 - 14} Q {mid},{y2 - 110} {x1},{y1 - 14}"/></g>'
        f'<g font-size="16"><text x="0" y="0">🦜</text>'
        f'<animateMotion dur="18s" repeatCount="indefinite" path="M -20,70 q {W / 2},-30 {W + 40},20"/></g>'
    )


ACTIVITIES = {
    "sleeping": "fast asleep 💤",
    "eating": "having bananas",
    "swinging": "swinging through the canopy",
    "running": "doing zoomies",
    "playing": "juggling his lunch",
    "jumping": "hopping between trees",
}


def pick_activity(hour):
    if hour >= 22 or hour < 6:
        return "sleeping"
    if hour < 8:
        return "eating"
    if hour < 11:
        return "swinging"
    if hour < 13:
        return "eating"
    if hour < 16:
        return "running"
    if hour < 19:
        return "playing"
    return "jumping"


def main():
    now = datetime.datetime.now(zoneinfo.ZoneInfo("America/New_York"))
    act = pick_activity(now.hour)
    fed = bananas_today()

    sky_svg, night = sky(now.hour)
    t1_svg, t1 = tree(140, night, 1.0)
    t2_svg, t2 = tree(760, night, 0.92)
    bush = f'<circle cx="460" cy="{GROUND_Y - 4}" r="22" fill="{"#174a21" if night else "#27863a"}"/>'

    status = f"Mojo is {ACTIVITIES[act]} · {now.strftime('%-I:%M %p')} in Charlotte"
    if fed is not None:
        status += f" · fed {fed} 🍌 today" if fed else " · hungry — a git push feeds him 🍌"

    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
        f'role="img" aria-label="Mojo the monkey, currently {ACTIVITIES[act]}">'
        + sky_svg
        + ground(night)
        + t1_svg
        + t2_svg
        + bush
        + monkey_scene(act, t1, t2, night)
        + f'<text x="{W / 2}" y="{H - 12}" font-size="13" text-anchor="middle" '
        f'fill="{"#cdd9f0" if night else "#1b4d27"}" font-family="ui-monospace, monospace">{status}</text>'
        + "</svg>"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"monkey-life.svg written — {act} at {now:%H:%M %Z}, fed={fed}")


if __name__ == "__main__":
    main()
